
// Enhanced saved addresses with 10 addresses from different countries
export const savedAddresses = [
  {
    id: 1,
    name: "Home",
    firstName: "John",
    lastName: "Doe",
    email: "john@example.com",
    address: "123 Fifth Avenue",
    city: "New York",
    state: "NY",
    zipCode: "10011",
    country: "United States",
    default: true
  },
  {
    id: 2,
    name: "Work",
    firstName: "John",
    lastName: "Doe",
    email: "john@example.com",
    address: "456 Market St",
    city: "San Francisco",
    state: "CA",
    zipCode: "94105",
    country: "United States",
    default: false
  },
  {
    id: 3,
    name: "Parents",
    firstName: "John",
    lastName: "Doe",
    email: "john@example.com",
    address: "789 Lake Shore Drive",
    city: "Chicago",
    state: "IL",
    zipCode: "60601",
    country: "United States",
    default: false
  },
  {
    id: 4,
    name: "Vacation Home",
    firstName: "John",
    lastName: "Doe",
    email: "john@example.com",
    address: "555 Ocean Drive",
    city: "Miami",
    state: "FL",
    zipCode: "33139",
    country: "United States",
    default: false
  },
  {
    id: 5,
    name: "London Flat",
    firstName: "John",
    lastName: "Doe",
    email: "john@example.com",
    address: "42 Oxford Street",
    city: "London",
    state: "England",
    zipCode: "W1D 1LY",
    country: "United Kingdom",
    default: false
  },
  {
    id: 6,
    name: "Paris Apartment",
    firstName: "John",
    lastName: "Doe",
    email: "john@example.com",
    address: "15 Rue de Rivoli",
    city: "Paris",
    state: "Île-de-France",
    zipCode: "75001",
    country: "France",
    default: false
  },
  {
    id: 7,
    name: "Tokyo Office",
    firstName: "John",
    lastName: "Doe",
    email: "john@example.com",
    address: "1-1-2 Otemachi",
    city: "Tokyo",
    state: "Tokyo",
    zipCode: "100-0004",
    country: "Japan",
    default: false
  },
  {
    id: 8,
    name: "Sydney Beach House",
    firstName: "John",
    lastName: "Doe",
    email: "john@example.com",
    address: "42 Bondi Road",
    city: "Sydney",
    state: "New South Wales",
    zipCode: "2026",
    country: "Australia",
    default: false
  },
  {
    id: 9,
    name: "Berlin Loft",
    firstName: "John",
    lastName: "Doe",
    email: "john@example.com",
    address: "10 Unter den Linden",
    city: "Berlin",
    state: "Berlin",
    zipCode: "10117",
    country: "Germany",
    default: false
  },
  {
    id: 10,
    name: "Toronto Condo",
    firstName: "John",
    lastName: "Doe",
    email: "john@example.com",
    address: "301 Front Street West",
    city: "Toronto",
    state: "Ontario",
    zipCode: "M5V 2T6",
    country: "Canada",
    default: false
  }
];
